export enum UserRole {
  CAM = "CAM",
  SALES = "SALES",
  ACCOUNTS = "ACCOUNTS",
  HOD = "HOD",
  IT_ADMIN = "IT_ADMIN",
  SYSTEM_ADMIN = "SYSTEM_ADMIN",
}

export enum PartySource {
  EXISTING_CUSTOMER = "EXISTING_CUSTOMER",
  POTENTIAL_CUSTOMER = "POTENTIAL_CUSTOMER",
  MCA_PORTAL = "MCA_PORTAL",
  NEW_PROSPECT = "NEW_PROSPECT",
  REFERENCE = "REFERENCE",
  INBOUND = "INBOUND",
  MARKET_VISIT = "MARKET_VISIT",
  INTERNET_SEARCH = "INTERNET_SEARCH",
}

export enum PartyStatus {
  // LEAD = "LEAD",
  // PLANNED = "PLANNED",
  // VISITED = "VISITED",
  // POTENTIAL = "POTENTIAL",
  // HIGH_POTENTIAL = "HIGH_POTENTIAL",
  // NOT_INTERESTED = "NOT_INTERESTED",
  // DORMANT = "DORMANT",
  // CONVERTED = "CONVERTED",
  // CUSTOMER = "CUSTOMER"
  LEAD = "LEAD",
  PLANNED = "PLANNED",
  VISITED = "VISITED",
  POTENTIAL = "POTENTIAL",
  HIGH_POTENTIAL = "HIGH_POTENTIAL",
  CONVERTED = "CONVERTED",
  CUSTOMER = "CUSTOMER",
  NOT_INTERESTED = "NOT_INTERESTED",
  DORMANT = "DORMANT",
}

export enum VisitPlanStatus {
  DRAFT = "DRAFT",
  SUBMITTED = "SUBMITTED",
  APPROVED = "APPROVED",
  REJECTED = "REJECTED",
  COMPLETED = "COMPLETED",
  CANCELLED = "CANCELLED",
}

export enum VisitReportStatus {
  DRAFT = "DRAFT",
  SUBMITTED = "SUBMITTED",
}

export enum ActivityType {
  PHONE_CALL = "PHONE_CALL",
  EMAIL = "EMAIL",
  WHATSAPP = "WHATSAPP",
  VISIT = "VISIT",
  OFFER = "OFFER",
  PRICE_COMMUNICATION = "PRICE_COMMUNICATION",
  NOTE = "NOTE",
}

export enum ApprovalEntityType {
  VISIT_PLAN = "VISIT_PLAN",
  ONBOARDING = "ONBOARDING",
}

export enum ApprovalStatus {
  PENDING = "PENDING",
  APPROVED = "APPROVED",
  REJECTED = "REJECTED",
  RETURNED_FOR_CORRECTION = "RETURNED_FOR_CORRECTION",
}

export enum OnboardingSource {
  POTENTIAL_CUSTOMER = "POTENTIAL_CUSTOMER",
  MCA_PORTAL = "MCA_PORTAL",
  NEW_PROSPECT = "NEW_PROSPECT",
}

export enum OnboardingStatus {
  DRAFT = "DRAFT",
  GST_VERIFICATION_PENDING = "GST_VERIFICATION_PENDING",
  READY_FOR_REVIEW = "READY_FOR_REVIEW",
  SUBMITTED = "SUBMITTED",
  PENDING_APPROVAL = "PENDING_APPROVAL",
  APPROVED = "APPROVED",
  REJECTED = "REJECTED",
  ERP_SYNC_PENDING = "ERP_SYNC_PENDING",
  CUSTOMER_CREATED = "CUSTOMER_CREATED",
  SYNC_FAILED = "SYNC_FAILED",
}

export enum DocumentType {
  GST_CERTIFICATE = "GST_CERTIFICATE",
  TRADE_DECLARATION = "TRADE_DECLARATION",
}

export enum GstVerificationStatus {
  NOT_STARTED = "NOT_STARTED",
  PENDING = "PENDING",
  VERIFIED_ACTIVE = "VERIFIED_ACTIVE",
  VERIFIED_INACTIVE = "VERIFIED_INACTIVE",
  MISMATCH = "MISMATCH",
  FAILED = "FAILED",
}

export enum ErpSyncStatus {
  NOT_READY = "NOT_READY",
  READY = "READY",
  PENDING = "PENDING",
  SUCCESS = "SUCCESS",
  FAILED = "FAILED",
}
